train:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 50
        p: 0.2
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 50
        p: 1.0
