_target_: src.model.DeepSpeech2Model
n_feats: 128
conv_channels: 32
n_rnn_layers: 4
rnn_hidden_size: 650
rnn_type:
    _target_: hydra.utils.get_class
    path: torch.nn.GRU
rnn_bidirectional: True
rnn_dropout: 0.1
fc_hidden_size: 1300
